### ISSUE TITLE
remote crashes latest forked-daapd

### ISSUE THREAD

**Issue by snizzleorg** [ejurgensen/forked-daapd#106]
just got the latest forked-daapd to check out the mpc functionality but now it keeps crashing when I try to connect with remote app:

that's the log:
```
[2015-02-22 23:03:24] [  LOG]  spotify: Track not available for playback: 'Tama Ngnogon'
[2015-02-22 23:03:27] [  LOG]  spotify: Track not available for playback: 'Batkallim: The Sun Of Egypt - Cheb i Sabbah Remix'
[2015-02-22 23:03:27] [  LOG]  spotify: Track not available for playback: 'Batkallim: The Sun Of Egypt - Cheb i Sabbah Remix'
[2015-02-22 23:03:27] [  LOG]  spotify: Track not available for playback: 'Lé Zaalen?'
[2015-02-22 23:03:28] [  LOG]  spotify: Track not available for playback: 'Pintar el Sol (Remix of Mi[2015-02-22 23:06:51] [  LOG]     mdns: Avahi state change: Client running
[2015-02-22 23:06:51] [  LOG]       db: Now vacuuming database, this may take some time...
[2015-02-22 23:06:52] [  LOG]       db: Database OK with 14904 active files and 48 active playlists
[2015-02-22 23:06:54] [  LOG]   remote: Read Remote pairing data (name 'iphone4', pin '2223') from /mnt/tank0/iTunes/Music/iphone4.remote
[2015-02-22 23:06:54] [  LOG]   remote: Remote 'iphone4' not known from mDNS, ignoring
[2015-02-22 23:06:54] [  LOG]   remote: Read Remote pairing data (name 'retina', pin '3837') from /mnt/tank0/iTunes/Music/retina.remote
[2015-02-22 23:06:54] [  LOG]   remote: Remote 'retina' not known from mDNS, ignoring
[2015-02-22 23:06:54] [  LOG]     main: Forked Media Server Version 22.3 taking off
[2015-02-22 23:06:54] [  LOG]     main: mDNS init
[2015-02-22 23:06:54] [  LOG]     mdns: Avahi state change: Client running
[2015-02-22 23:06:54] [  LOG]       db: Now vacuuming database, this may take some time...
[2015-02-22 23:06:56] [  LOG]       db: Database OK with 14904 active files and 48 active playlists
[2015-02-22 23:06:57] [  LOG]   remote: Read Remote pairing data (name 'iphone4', pin '2223') from /mnt/tank0/iTunes/Music/iphone4.remote
[2015-02-22 23:06:57] [  LOG]   remote: Remote 'iphone4' not known from mDNS, ignoring
[2015-02-22 23:06:57] [  LOG]   remote: Read Remote pairing data (name 'retina', pin '3837') from /mnt/tank0/iTunes/Music/retina.remote
[2015-02-22 23:06:57] [  LOG]   remote: Remote 'retina' not known from mDNS, ignoring
[2015-02-22 23:06:57] [  LOG]   remote: Read Remote pairing data (name 'rubyremote', pin '1234') from /mnt/tank0/iTunes/Music/ruby.remote
[2015-02-22 23:06:57] [  LOG]   remote: Remote 'rubyremote' not known from mDNS, ignoring
[2015-02-22 23:06:57] [  LOG]   remote: Read Remote pairing data (name 'Gabrieles iPad', pin '8341') from /mnt/tank0/iTunes/Music/gabstarpad.remote
[2015-02-22 23:06:57] [  LOG]   remote: Remote 'Gabrieles iPad' not known from mDNS, ignoring
[2015-02-22 23:06:57] [  LOG]     scan: Scanned 200 files...
[2015-02-22 23:06:57] [  LOG]     scan: Scanned 400 files...
[2015-02-22 23:06:58] [  LOG]     scan: Scanned 600 files...
[2015-02-22 23:06:58] [  LOG]     scan: Scanned 800 files...
[2015-02-22 23:06:58] [  LOG]     scan: Scanned 1000 files...
[2015-02-22 23:06:58] [  LOG]     scan: Scanned 1200 files...
[2015-02-22 23:07:00] [  LOG]     scan: Scanned 3800 files...
[2015-02-22 23:07:00] [  LOG]     scan: Scanned 4000 files...
[2015-02-22 23:07:01] [  LOG]     scan: Scanned 4200 files...
[2015-02-22 23:07:01] [  LOG]     scan: Scanned 4400 files...
[2015-02-22 23:07:01] [  LOG]     scan: Scanned 4600 files...
[2015-02-22 23:07:01] [  LOG]     scan: Scanned 4800 files...
[2015-02-22 23:07:01] [  LOG]     scan: Scanned 5000 files...
[2015-02-22 23:07:01] [  LOG]     scan: Scanned 5200 files...
[2015-02-22 23:07:01] [  LOG]     main: Forked Media Server Version 22.3 taking off
[2015-02-22 23:07:01] [  LOG]     main: mDNS init
[2015-02-22 23:07:01] [  LOG]     mdns: Avahi state change: Client running
[2015-02-22 23:07:01] [  LOG]       db: Now vacuuming database, this may take some time...
nt/tank0/iTunes/Music/iphone4.remote
 /mnt/tank0/iTunes/Music/ruby.remote
[2015-02-22 23:07:04] [  LOG]   remote: Remote 'Gabrieles iPad' not known from mDNS, ignoring
[2015-02-22 23:07:04] [  LOG]     scan: Scanned 200 files...
[2015-02-22 23:07:04] [  LOG]     scan: Scanned 400 files...
[2015-02-22 23:07:04] [  LOG]     scan: Scanned 600 files...
[2015-02-22 23:07:04] [  LOG]     scan: Scanned 800 files...
[2015-02-22 23:07:05] [  LOG]     scan: Scanned 1000 files...
[2015-02-22 23:07:05] [  LOG]     scan: Scanned 1200 files...
[2015-02-22 23:07:05] [  LOG]     scan: Scanned 1400 files...
[2015-02-22 23:07:05] [  LOG]     main: Forked Media Server Version 22.3 taking off
[2015-02-22 23:07:05] [  LOG]     main: mDNS init
[2015-02-22 23:07:05] [  LOG]     mdns: Avahi state change: Client running
[2015-02-22 23:07:05] [  LOG]       db: Now vacuuming database, this may take some time...
[2015-02-22 23:07:07] [  LOG]       db: Database OK with 14904 active files and 48 active playlists
[2015-02-22 23:07:08] [  LOG]   remote: Read Remote pairing data (name 'iphone4', pin '2223') from /mnt/tank0/iTunes/Music/iphone4.remote
[2015-02-22 23:07:08] [  LOG]   remote: Remote 'iphone4' not known from mDNS, ignoring
[2015-02-22 23:07:08] [  LOG]   remote: Read Remote pairing data (name 'retina', pin '3837') from /mnt/tank0/iTunes/Music/retina.remote
[2015-02-22 23:07:08] [  LOG]   remote: Remote 'retina' not known from mDNS, ignoring
[2015-02-22 23:07:08] [  LOG]   remote: Read Remote pairing data (name 'rubyremote', pin '1234') from /mnt/tank0/iTunes/Music/ruby.remote
[2015-02-22 23:07:08] [  LOG]   remote: Remote 'rubyremote' not known from mDNS, ignoring
[2015-02-22 23:07:08] [  LOG]   remote: Read Remote pairing data (name 'Gabrieles iPad', pin '8341') from /mnt/tank0/iTunes/Music/gabstarpad.remote
[2015-02-22 23:07:08] [  LOG]   remote: Remote 'Gabrieles iPad' not known from mDNS, ignoring
[2015-02-22 23:07:08] [  LOG]     scan: Scanned 200 files...
[2015-02-22 23:07:08] [  LOG]     scan: Scanned 400 files...
[2015-02-22 23:07:08] [  LOG]     scan: Scanned 600 files...
[2015-02-22 23:07:08] [  LOG]     scan: Scanned 800 files...
[2015-02-22 23:07:08] [  LOG]     scan: Scanned 1000 files...
[2015-02-22 23:07:09] [  LOG]     scan: Scanned 1200 files...
[2015-02-22 23:07:11] [  LOG]     scan: Scanned 3800 files...
[2015-02-22 23:07:11] [  LOG]     scan: Scanned 4000 files...
[2015-02-22 23:07:11] [  LOG]     scan: Scanned 4200 files...
[2015-02-22 23:07:11] [  LOG]     scan: Scanned 4400 files...
[2015-02-22 23:07:11] [  LOG]     scan: Scanned 4600 files...
[2015-02-22 23:07:11] [  LOG]     scan: Scanned 4800 files...
[2015-02-22 23:07:12] [  LOG]     scan: Scanned 5000 files...
[2015-02-22 23:07:12] [  LOG]     scan: Scanned 5200 files...
[2015-02-22 23:07:12] [  LOG]     main: Forked Media Server Version 22.3 taking off
[2015-02-22 23:07:12] [  LOG]     main: mDNS init
[2015-02-22 23:07:12] [  LOG]     mdns: Avahi state change: Client running
[2015-02-22 23:07:14] [  LOG]   remote: Read Remote pairing data (name 'rubyremote', pin '1234') fromfrom /mnt/tank0/iTunes/Music/gabstarpad.remote
[2015-02-22 23:07:14] [  LOG]   remote: Remote 'Gabrieles iPad' not known from mDNS, ignoring
[2015-02-22 23:07:15] [  LOG]     scan: Scanned 200 files...
[2015-02-22 23:07:15] [  LOG]     scan: Scanned 400 files...
```
It actually keeps restarting as upstart re-spawns

any ideas where to look for what?

**Comment by snizzleorg** [comment]
I tried deleting the database but that did not help

**Comment by protree** [comment]
Same thing happens to me when connecting with iTunes 12.1.0.50.

Log:

```
[2015-02-23 01:43:22] [DEBUG]       db: Done with post-scan DB maintenance
[2015-02-23 01:43:33] [DEBUG]     daap: DAAP request: /server-info
[2015-02-23 01:43:33] [DEBUG]     daap: DAAP request handled in 1 milliseconds
[2015-02-23 01:43:33] [DEBUG]     daap: DAAP request: /login
[2015-02-23 01:43:33] [DEBUG]     daap: DAAP request handled in 0 milliseconds
[2015-02-23 01:43:33] [DEBUG]    httpd: Found query string
[2015-02-23 01:43:33] [DEBUG]     daap: DAAP request: /update?session-id=100&revision-number=1&delta=0
[2015-02-23 01:43:33] [DEBUG]     daap: DAAP request handled in 1 milliseconds
[2015-02-23 01:43:33] [DEBUG]    httpd: Found query string
[2015-02-23 01:43:33] [DEBUG]     daap: DAAP request: /databases?session-id=100&revision-number=2&delta=0
[2015-02-23 01:43:33] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0;'
[2015-02-23 01:43:33] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM playlists p WHERE p.disabled = 0;'
[2015-02-23 01:43:33] [DEBUG]     daap: DAAP request handled in 28 milliseconds
[2015-02-23 01:43:33] [DEBUG]    httpd: Found query string
[2015-02-23 01:43:33] [DEBUG]     daap: DAAP request: /databases/1/items?session-id=100&revision-number=2&delta=0&type=music&meta=all
[2015-02-23 01:43:34] [ INFO]    cache: Cache hit: /databases/1/items?delta=0&type=music&meta=all
[2015-02-23 01:43:36] [DEBUG]    httpd: Found query string
[2015-02-23 01:43:36] [DEBUG]     daap: DAAP request: /databases/1/containers?session-id=100&revision-number=2&delta=0&meta=dmap.itemid,dmap.itemname,dmap.persistentid,dmap.parentcontainerid,com.apple.itunes.is-podcast-playlist,com.apple.itunes.special-playlist,com.apple.itunes.smart-playlist,dmap.haschildcontainers,com.apple.itunes.saved-genius
[2015-02-23 01:43:36] [DEBUG]     daap: Asking for 9 meta tags
[2015-02-23 01:43:36] [ WARN]     daap: Could not find requested meta field 'dmap.haschildcontainers'
[2015-02-23 01:43:36] [ WARN]     daap: Could not find requested meta field 'com.apple.itunes.saved-genius'
[2015-02-23 01:43:36] [DEBUG]     daap: Found 7 meta tags
[2015-02-23 01:43:36] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM playlists p WHERE p.disabled = 0;'
[2015-02-23 01:43:36] [DEBUG]       db: Starting query 'SELECT f.* FROM playlists f WHERE f.disabled = 0 ORDER BY f.type DESC, f.special_id ASC, f.title ASC LIMIT -1 OFFSET 0;'
[2015-02-23 01:43:36] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND 1 = 1;'
[2015-02-23 01:43:36] [DEBUG]     daap: Done with playlist
[2015-02-23 01:43:36] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND f.media_kind = 4;'
[2015-02-23 01:43:36] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND f.media_kind = 2;'
[2015-02-23 01:43:36] [DEBUG]     daap: Done with playlist
[2015-02-23 01:43:36] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND f.media_kind = 64;'
[2015-02-23 01:43:37] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND f.media_kind = 1;'
[2015-02-23 01:43:37] [DEBUG]     daap: Done with playlist
[2015-02-23 01:43:37] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND f.media_kind = 8;'
[2015-02-23 01:43:37] [DEBUG]       db: End of query results
[2015-02-23 01:43:37] [DEBUG]     daap: Done with playlist list, 3 playlists
[2015-02-23 01:43:37] [DEBUG]     daap: DAAP request handled in 133 milliseconds
[2015-02-23 01:43:37] [  LOG]     main: Forked Media Server Version 22.3 taking off
[2015-02-23 01:43:37] [DEBUG]     main: Initialized with gcrypt 1.5.3
[2015-02-23 01:43:37] [  LOG]     main: mDNS init
[2015-02-23 01:43:37] [DEBUG]     mdns: Initializing Avahi mDNS
[2015-02-23 01:43:37] [  LOG]     mdns: Avahi state change: Client running
[2015-02-23 01:43:37] [DEBUG]     mdns: Creating service group
[2015-02-23 01:43:37] [DEBUG]     mdns: No entries yet... skipping service create
[2015-02-23 01:43:37] [ INFO]     main: Initializing database
[2015-02-23 01:43:37] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'schema_version_major';'
[2015-02-23 01:43:37] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'schema_version_minor';'
[2015-02-23 01:43:37] [  LOG]       db: Now vacuuming database, this may take some time...
[2015-02-23 01:43:38] [DEBUG]       db: Running query 'ANALYZE;'
[2015-02-23 01:43:38] [DEBUG]       db: Playlist title for config item 'name_library' set with query 'UPDATE playlists SET title = 'Library' WHERE type = 1 AND special_id = 0;'
[2015-02-23 01:43:38] [DEBUG]       db: Playlist title for config item 'name_music' set with query 'UPDATE playlists SET title = 'Music' WHERE type = 1 AND special_id = 6;'
[2015-02-23 01:43:38] [DEBUG]       db: Playlist title for config item 'name_movies' set with query 'UPDATE playlists SET title = 'Movies' WHERE type = 1 AND special_id = 4;'
[2015-02-23 01:43:38] [DEBUG]       db: Playlist title for config item 'name_tvshows' set with query 'UPDATE playlists SET title = 'TV Shows' WHERE type = 1 AND special_id = 5;'
[2015-02-23 01:43:39] [DEBUG]       db: Playlist title for config item 'name_podcasts' set with query 'UPDATE playlists SET title = 'Podcasts' WHERE type = 1 AND special_id = 1;'
[2015-02-23 01:43:39] [DEBUG]       db: Playlist title for config item 'name_audiobooks' set with query 'UPDATE playlists SET title = 'Audiobooks' WHERE type = 1 AND special_id = 7;'
```

forked-daapd-version: latest master with --enable-mpd
OS: Ubuntu 14.04.2 LTS 64 Bit

**Comment by protree** [comment]
also happens without --enable-mpd

**Comment by snizzleorg** [comment]
well iTunes crashes it as well. I don't care so much about iTunes though anymore since there is forked-daapd ;-)

**Comment by chme** [comment]
I can reproduce the error on my ubuntu laptop. I did not notice this earlier, because i always set the compiler flags from "-O2" to "-O0". With "-O0" the segfault (at least on my machine) does not happen.

The cause must be one of the changes i made in db.c. I try to locate and fix it.

**Comment by snizzleorg** [comment]
So how do I set the compile fags to circumvent this? and what do they mean?

**Comment by chme** [comment]
I think i found the cause and pr #107 should fix it. Would be great if you could test if it works for you.

**Comment by snizzleorg** [comment]
so I have to switch branches since its not yet merged - right ?

**Comment by snizzleorg** [comment]
well i pulled chme's repo 
```
https://github.com/chme/forked-daapd.git
```

but it still crashes when I try to connect with remote

**Comment by chme** [comment]
Did you switch to the branch 'mpdfixes' (my master branch is identical to ejurgensens master branch)? 

```
git checkout origin/mpdfixes
```

**Comment by chme** [comment]
If you switched to the branch and it still crashes, can you please check if the log shows the same messages?

**Comment by ejurgensen** [comment]
Thanks for reporting the bug, snizzleorg and protree, and thanks for the quick fix, chme! I've merged it with master now. And yes, please do report if you still have problems.

**Comment by protree** [comment]
You're welcome! Testing right now, dp-update v15.1 -> v16.0 takes very long...

**Comment by snizzleorg** [comment]
It's working! thanks for the very quick fix!

**Comment by protree** [comment]
Works! But database upgrade didn't work, took forever. I will look into this later with debug-log

**Comment by snizzleorg** [comment]
I didn't notice any problems with the data base. Has the update to be triggered somehow?
