### ISSUE TITLE
Embedded PNG artwork fails to load

### ISSUE THREAD

**Issue by main--** [ejurgensen/forked-daapd#345]
All of the artwork in my library is embedded and a lot of it is song-specific. One of the first things I noticed when I started using this is that while most of it shows up properly, for some songs it doesn't. I manually checked it a few times and the only trend I was able to spot is that the broken artworks were PNG while the working ones were JPEG.

**Comment by ejurgensen** [comment]
Thanks for report. Yes, I could reproduce this. I believe it is now fixed with the above commit. Let me know if it works.

**Comment by main--** [comment]
Still broken for me.

I didn't actually read the code, but your commit sets the format to `AV_PIX_FMT_RGB24` while ffprobe says that my song artwork is actually `AV_PIX_FMT_RGBA` (`Stream #0:1: Video: png, rgba(pc), 1280x720, 90k tbr, 90k tbn, 90k tbc`). Perhaps that's why it doesn't work?

**Comment by ejurgensen** [comment]
I'm setting the output pixel format, not the input, and ffmpeg should be able to convert, but perhaps sws_getcontext() doesn't like the combination of RGBA -> RBG24.

What sort of error message are you seeing in the log? (if there is nothing, then perhaps it is just the cache that needs to be cleared)

**Comment by main--** [comment]
I tested this on a clean database and cache. When adding a song, I see this:

```
[DEBUG]   ffmpeg: Setting default whitelist 'file,crypto'
[DEBUG]   ffmpeg: Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[DEBUG]   ffmpeg: ISO: File Type Major Brand: M4A 
[DEBUG]   ffmpeg: Unknown dref type 0x08206c7275 size 12
[ WARN]   ffmpeg: stream 0, timescale not set
[DEBUG]   ffmpeg: Before avformat_find_stream_info() pos: 1498890 bytes read:1040351 seeks:1 nb_streams:2
[DEBUG]   ffmpeg: demuxer injecting skip 2112 / discard 0
[DEBUG]   ffmpeg: skip 2112 / discard 0 samples due to side data
[DEBUG]   ffmpeg: skip whole frame, skip left: 1088
[DEBUG]   ffmpeg: All info found
[DEBUG]   ffmpeg: After avformat_find_stream_info() pos: 1498896 bytes read:1040351 seeks:1 frames:2
[DEBUG]     scan: File has 2 streams
[DEBUG]     scan: Found embedded artwork (stream 1)
[DEBUG]     scan: Duration 186316 ms, bitrate 330 kbps
[DEBUG]     scan: samplerate 44100, bps 32
[DEBUG]     scan: AAC
[DEBUG]     scan: Picked up 2 tags from file metadata
[DEBUG]     scan: Picked up 0 tags from audio stream metadata
[DEBUG]     scan: Picked up 2 tags with generic md_map, 2 tags total
[DEBUG]   ffmpeg: Statistics: 1040351 bytes read, 1 seeks
[DEBUG]       db: Running query 'INSERT INTO files (id, path, fname, title, artist, album, genre, comment, type, composer, orchestra, conductor, grouping, url, bitrate, samplerate, song_length, file_size, year, track, total_tracks, disc, total_discs, bpm, compilation, artwork, rating, play_count, seek, data_kind, item_kind, description, time_added, time_modified, time_played, db_timestamp, disabled, sample_count, codectype, idx, has_video, contentrating, bits_per_sample, album_artist, media_kind, tv_series_name, tv_episode_num_str, tv_network_name, tv_episode_sort, tv_season_num,  songartistid, songalbumid,  title_sort, artist_sort, album_sort, composer_sort, album_artist_sort, virtual_path, directory_id, date_released)  VALUES (NULL, '/tmp/music/Adam Tell - Two Somethings (feat. Em 1.m4a', 'Adam Tell - Two Somethings (feat. Em 1.m4a', TRIM('Adam Tell - Two Somethings (feat. Emily Solo)'), TRIM('Unknown artist'), TRIM('Unknown album'), TRIM('Unknown genre'), TRIM(NULL), 'm4a', TRIM(NULL), TRIM(NULL), TRIM(NULL), TRIM(NULL), NULL, 330, 44100, 186316, 7695373, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 'AAC audio file', 1485441899, 1485441898, 0, 1485441899, 0, 0, 'mp4a', 0, 0, 0, 32, TRIM('Unknown artist'), 1, TRIM(NULL), TRIM(NULL), TRIM(NULL), 0, 0, daap_songalbumid(LOWER(TRIM('Unknown artist')), ''), daap_songalbumid(LOWER(TRIM('Unknown artist')), LOWER(TRIM('Unknown album'))),  TRIM('Adam Tell - Two Somethings (feat. Emily Solo)'), TRIM('Unknown artist'), TRIM('Unknown album'), TRIM(NULL), TRIM('Unknown artist'), TRIM('/file:/tmp/music/Adam Tell - Two Somethings (feat. Em 1.m4a'), 6, 0);'
[DEBUG]    cache: Running query 'UPDATE artwork SET db_timestamp = 1485441899 WHERE filepath = '/tmp/music/Adam Tell - Two Somethings (feat. Em 1.m4a' AND db_timestamp >= 1485441898;'
[DEBUG]    cache: Running query 'DELETE FROM artwork WHERE filepath = '/tmp/music/Adam Tell - Two Somethings (feat. Em 1.m4a' AND db_timestamp < 1485441898;'
```

Then, when I connect with iTunes Remote and see that the artwork is missing:

```
[DEBUG]     daap: DAAP request: /databases/1/items/1/extra_data/artwork?mw=100&mh=100&session-id=511455110
[DEBUG]  artwork: Artwork request for item 1
[DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND id = 1;'
[DEBUG]       db: Starting query 'SELECT f.* FROM files f WHERE f.disabled = 0 AND id = 1  ;'
[DEBUG]    cache: Running query 'SELECT a.format, a.data FROM artwork a WHERE a.type = 1 AND a.persistentid = 1 AND a.max_w = 100 AND a.max_h = 100;'
[DEBUG]    cache: No results
[DEBUG]   ffmpeg: Setting default whitelist 'file,crypto'
[DEBUG]   ffmpeg: Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[DEBUG]   ffmpeg: ISO: File Type Major Brand: M4A 
[DEBUG]   ffmpeg: Unknown dref type 0x08206c7275 size 12
[ WARN]   ffmpeg: stream 0, timescale not set
[DEBUG]   ffmpeg: Before avformat_find_stream_info() pos: 1498890 bytes read:1040351 seeks:1 nb_streams:2
[DEBUG]   ffmpeg: demuxer injecting skip 2112 / discard 0
[DEBUG]   ffmpeg: skip 2112 / discard 0 samples due to side data
[DEBUG]   ffmpeg: skip whole frame, skip left: 1088
[DEBUG]   ffmpeg: All info found
[DEBUG]   ffmpeg: After avformat_find_stream_info() pos: 1498896 bytes read:1040351 seeks:1 frames:2
[DEBUG]  artwork: Original image dimensions: w 1280 h 720
[DEBUG]  artwork: Raw destination width 100 height 56
[DEBUG]  artwork: Destination width 100 height 56
[DEBUG]  artwork: Artwork buffer size: 2764800
[DEBUG]   ffmpeg: Forcing full internal H chroma due to input having non subsampled chroma
[ WARN]   ffmpeg: AVFrame.format is not set
[ WARN]   ffmpeg: AVFrame.width or height is not set
[ WARN]   ffmpeg: Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[ WARN]   ffmpeg: Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[ WARN]   ffmpeg: Encoder did not produce proper pts, making some up.
[DEBUG]   ffmpeg: Statistics: 1040351 bytes read, 1 seeks
[DEBUG]  artwork: Artwork for 'Adam Tell - Two Somethings (feat. Emily Solo)' found in source 'embedded'
[DEBUG]     daap: DAAP request handled in 39 milliseconds
```

When playing the song, I actually notice a difference though: I now see a black cover instead of the iTunes placeholder artwork.
