### ISSUE TITLE
Audio not playing on ATV4 tvOS 11.2.6

### ISSUE THREAD

**Issue by BenMation** [ejurgensen/forked-daapd#508]
Hello guys,

My forked-daapd server is working for all my other airplay-enabled speakers. However for my Apple TV4, the display shows that it is reading from my pipe but there is no audio output.
I am currently using shairport-sync to receive airplay request from my macbook or iphone, which is then fed to a pipe where forked-daapd will pick up the audio from. I am currently running forked-daapd version 26

Below is what the log file shows.

[DEBUG]     raop: Got retransmit request from 'Apple TV', seq_start 301 len 1
[ WARN]     raop: Device 'Apple TV' asking for seqnum 301; not in buffer (h 565 t 65102)
[DEBUG]     raop: Got retransmit request from 'Apple TV', seq_start 302 len 1
[ WARN]     raop: Device 'Apple TV' asking for seqnum 302; not in buffer (h 565 t 65102)
[ SPAM]   laudio: Sync 0 cur_pos 5221882218, pb_pos 5221872009 (diff 209, delay 98103), pos 5221882112
[ SPAM]   laudio: Sync 0 cur_pos 5221926577, pb_pos 5221916369 (diff 208, delay 98095), pos 5221926464
[ SPAM]   laudio: Sync 0 cur_pos 5221970925, pb_pos 5221960719 (diff 206, delay 98097), pos 5221970816
[ SPAM]   laudio: Sync 0 cur_pos 5222015272, pb_pos 5222005073 (diff 199, delay 98095), pos 5222015168
[ SPAM]   laudio: Sync 0 cur_pos 5222059633, pb_pos 5222049433 (diff 200, delay 98087), pos 5222059520
[DEBUG]   player: Input buffer has 20900 bytes
[DEBUG]     raop: Building SET_PARAMETER for 'Apple TV'
[ SPAM]   laudio: Sync 0 cur_pos 5222103975, pb_pos 5222093772 (diff 203, delay 98100), pos 5222103872
[ SPAM]   laudio: Sync 0 cur_pos 5222148386, pb_pos 5222138182 (diff 204, delay 98042), pos 5222148224
[ SPAM]   laudio: Sync 0 cur_pos 5222192683, pb_pos 5222182482 (diff 201, delay 98094), pos 5222192576
[ SPAM]   laudio: Sync 0 cur_pos 5222237029, pb_pos 5222226831 (diff 198, delay 98097), pos 5222236928
[ SPAM]   laudio: Sync 0 cur_pos 5222281389, pb_pos 5222271190 (diff 199, delay 98090), pos 5222281280
[DEBUG]     raop: Got retransmit request from 'Apple TV', seq_start 1903 len 1

Any form of help is much appreciated. Thanks in advance!

**Comment by ejurgensen** [comment]
Sorry, the log doesn't really reveal much as to what is going on. A few retransmit requests are not unusual.

There was a previous issue with ATV4 which was solved by the user disabling ipv6 in forked-daapd's config. Does that also work for you?

**Comment by BenMation** [comment]
@ejurgensen I have tried disabling the ipv6 option in the config file and it still does not work. Is there any troubleshooting that I can do to help? If it helps, I can send a photo of what appears on the ATV4 once I get back to my machine.

**Comment by ejurgensen** [comment]
No that won’t help me. I would need either some clue from the log, or to get hold of a atv4 to reproduce.

**Comment by BenMation** [comment]
I will copy the full log details once I get back to my workstation hopefully by monday. Hopefully it would shed some light to the issue. Thanks in advance :)

**Comment by BenMation** [comment]
[forkeddaapdlog.pdf](https://github.com/ejurgensen/forked-daapd/files/1824482/forkeddaapdlog.pdf)

attached is the log file

**Comment by ejurgensen** [comment]
pdf?

**Comment by BenMation** [comment]
Hi there, i managed to resolve the issue after a reinstall and is not able to reproduce the issue
