### ISSUE TITLE
iTunes metadata parse error

### ISSUE THREAD

**Issue by jptrsn** [ejurgensen/forked-daapd#683]
When importing metadata from iTunes playlists into a new songs database, I'm seeing negative values populated for the `time_played` field.

To reproduce the issue:

1. Enable iTunes metadata override
2. Stop the service
3. Delete the songs3.db file
3. Restart the service
4. Allow the first scan to complete
5. Open the songs3.db file in sqlite3
6. Run this query and observe the results: `select title,play_count,time_played from files order by time_played limit 5;`

I see negative values for songs, likely because the field type is a mismatch between "seconds since 1970" and "milliseconds since 1970", possibly related to #593

**Comment by ejurgensen** [comment]
Yes, you are probably right. Can you add some info about what the value of time_played is in the XML file? And what the corresponding negative value is in the db? Just for a track or two.

**Comment by jptrsn** [comment]
From the database:
```
select title,time_played from files order by time_played limit 5;
Be Back Ta-Reckla|-816528866
Strangers|-811096871
Elysium|-809614702
Half Day Closing|-805589405
It's A Fire|-804412572
```

From iTunes XML:

*Be Back Ta-Reckla*
```
<key>Play Date</key><integer>3478438430</integer>
<key>Play Date UTC</key><date>2014-03-23T20:53:50Z</date>
```
*Strangers*
```
<key>Play Date</key><integer>3483870425</integer>
<key>Play Date UTC</key><date>2014-05-25T17:47:05Z</date>
```
*Elysium*
```
<key>Play Date</key><integer>3485352594</integer>
<key>Play Date UTC</key><date>2014-06-11T21:29:54Z</date>
```
*Half Day Closing*
```
<key>Play Date</key><integer>3489377891</integer>
<key>Play Date UTC</key><date>2014-07-28T11:38:11Z</date>
```
*It's A Fire*
```
<key>Play Date</key><integer>3490554724</integer>
<key>Play Date UTC</key><date>2014-08-11T02:32:04Z</date>
```

**Comment by ejurgensen** [comment]
Of course Apple is using their own timestamp standard! It seems to be seconds since 1904, which is apparently called a Mac HFS+ timestamp.

Should be simple enough to fix. I also need to look at why those values become negative (looks like it is treated as a signed integer, but it should be an unsigned one).

**Comment by ejurgensen** [comment]
Should be fixed now, thanks for reporting. Note that to correct the values in your db you will need to trigger the filescanner (you can for instance run "touch your_itunes_file.xml" to do that).

**Comment by jptrsn** [comment]
Is there a new rPi build? I'm still showing `Version: 26.4.78.git1ae24dc-2` which doesn't appear to have changed after running `apt-get update`.

**Comment by ejurgensen** [comment]
Not yet, it will be a little while before I make the next one
